services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mundialdb
    volumes:
      - ./api/db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    ports:
      - '3307:3306'

  api:
    build:
      context: ./api
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: '3306'
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: mundialdb
    depends_on:
      - db

  web:
    build: ./web
    ports:
      - '8000:8000'
    environment:
      API_BASE_URL: http://localhost:3000
    depends_on:
      - api
    volumes:
      - ./web:/usr/src/app

volumes:
  db_data: